# Generated by Django 5.2.4 on 2025-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_plan_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingfeature',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='order',
            field=models.CharField(blank=True, null=True),
        ),
    ]
