# Generated by Django 5.2.4 on 2025-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_pricingfeature_options_pricingfeature_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingfeature',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
