# Generated by Django 5.2.4 on 2025-11-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='pricingfeature',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='services',
        ),
        migrations.RemoveField(
            model_name='pricingfeature',
            name='service',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='PricingFeature',
        ),
    ]
