# Generated by Django 5.2.4 on 2025-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(default='dd'),
        ),
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(default='dd'),
        ),
    ]
