# Generated by Django 5.2.8 on 2025-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_blog_conclusion_blog_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('numberPhone', models.CharField(max_length=100)),
                ('consultationSubject', models.CharField(max_length=100)),
                ('consultationContent', models.TextField()),
                ('paymentImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
      
        migrations.AlterUniqueTogether(
            name='savedprojects',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SavedProjects',
        ),
    ]
