# Generated by Django 5.2.8 on 2025-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_legalconsultation_remove_image_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalconsultation',
            name='consultationSubject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='legalconsultation',
            name='paymentImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
