# Generated by Django 5.2.8 on 2025-11-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profile_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='numberPhone',
        ),
    ]
